
    mysql:
        container_name: ss_mysql
        image: mysql:5.6
        volumes:
            - ~/Codebase/ssdb:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: pw
    phpfpm:
        container_name: ss_php
        build: docker-images/php/5.6-dev
        links:
            - 'mysql:mysql'
        volumes:
            # Ensure you have set this environment variable!
            - ${SS_ROOT_PATH}:/var/www
    nginx:
        container_name: ss_nginx
        build: docker-images/nginx
        ports:
            - '80:80'
            - '443:443'
        domainname: 127.0.0.1
        #domainname: ss3.test
        links:
            - phpfpm
            - mysql
            # - es
        volumes_from:
            - phpfpm